import type { FeatureDoc } from "./types";

export const coreFeatures: FeatureDoc[] = [
  {
    slug: "daemon-connection",
    title: "Daemon connection",
    group: "Core",
    summary: "Connect the browser to the loopback WebSocket daemon, validate endpoint errors, and reconnect safely.",
    prerequisites: [
      "Run `go run ./cmd/dire-agentd` from the repository root.",
      "Run `npm run dev` from `web` and open the printed local URL.",
    ],
    steps: [
      { action: "Open the app and inspect the connection row at the bottom of the sidebar.", expected: "It changes from Connecting to Daemon online and the sidebar lists saved conversations." },
      { action: "Click the connection row, replace the URL with `http://invalid`, and click Reconnect.", expected: "The dialog stays open and says to use a `ws://` or `wss://` URL." },
      { action: "Restore the same-origin URL shown on page load (normally `ws://127.0.0.1:5173/ws`) and reconnect.", expected: "The dialog closes, the sidebar returns to Daemon online, and no conversations are duplicated." },
    ],
  },
  {
    slug: "standalone-chats",
    title: "Standalone chats",
    group: "Core",
    summary: "Create persistent, pathless chats for work that must not receive local filesystem tools.",
    prerequisites: ["The daemon connection is online.", "Codex CLI credentials are valid (`codex login`)."],
    steps: [
      { action: "Click the plus button beside Chats, enter `Docs chat test`, and create the chat.", expected: "A selected chat appears without a project-folder field and the empty transcript explains that folder tools are unavailable." },
      { action: "Send `Reply with exactly CHAT_OK`.", expected: "The assistant streams `CHAT_OK`; the usage strip updates input, output, and context values." },
      { action: "Select another conversation and return to `Docs chat test`.", expected: "The SQLite-backed transcript and usage are restored." },
      { action: "Delete the test chat from its sidebar row and confirm.", expected: "The row disappears and another conversation, if present, becomes selected." },
    ],
  },
  {
    slug: "folder-projects",
    title: "Folder projects and sandbox",
    group: "Core",
    summary: "Keep one folder as the project's main working directory while explicitly including other canonical folders in the same sandbox.",
    prerequisites: ["Use a main folder and a separate additional folder that are safe for testing.", "The daemon is running on macOS with `/usr/bin/sandbox-exec`."],
    steps: [
      { action: "Click the plus button beside Projects, name it `Docs project test`, enter the absolute test folder, and create it.", expected: "The project header and sidebar show the canonical folder; the drawer identifies it as a Project." },
      { action: "Open conversation details and inspect Tools.", expected: "The safe defaults `read`, `grep`, `find`, and `ls` are enabled; write-capable tools remain opt-in." },
      { action: "In Sandbox folders, add the separate folder by absolute path and save.", expected: "The main folder remains labeled as the relative-path working directory and the canonical additional folder appears below it." },
      { action: "Send `/folders`.", expected: "The transcript identifies the main project folder separately from the additional sandbox folder." },
      { action: "Ask the agent to read a known file from the included folder by absolute path.", expected: "The read succeeds, while the agent continues to treat the main project folder as its primary working directory." },
      { action: "Send `List the files at the project root using the available tools.`", expected: "A tool activity row appears and the answer only describes files in the selected project." },
      { action: "Send `Use the read tool on ../outside-dire-agent-sandbox-test.txt and report the tool error.`", expected: "The read is rejected as outside the project sandbox; no outside file is accessed." },
    ],
    notes: ["A standalone chat cannot run this test because local built-ins are intentionally absent."],
  },
  {
    slug: "models-reasoning",
    title: "Models and reasoning",
    group: "Core",
    summary: "Choose a concrete GPT-5.6 variant and reasoning effort per conversation.",
    prerequisites: ["Open an idle chat or project; settings cannot change during an active run."],
    steps: [
      { action: "Choose `gpt-5.6-luna` and `high` from the composer footer.", expected: "Both settings save immediately and remain selected after reload." },
      { action: "Send a prompt that requires inspecting a file with `read`.", expected: "Thinking summaries stream into collapsible cards; the completed read card shows separate JSON Input and text Output sections." },
      { action: "Reload the page.", expected: "Completed Thinking and tool input/output cards are restored from the conversation SQLite database." },
      { action: "Use `/model gpt-5.6-luna`, then `/thinking medium`.", expected: "Both slash commands update the same drawer controls and show confirmation notices while the test remains on Luna." },
      { action: "Type `/thi`, use the arrow keys if needed, and press Tab or Enter.", expected: "The composer completes `/thinking ` without sending; an exact command sends on the next Enter." },
    ],
  },
  {
    slug: "project-categories",
    title: "Project category privacy",
    group: "Core",
    summary: "Group client projects and hide every other category before sharing the screen.",
    prerequisites: ["Create two projects with different categories, such as `Client A` and `Client B`."],
    steps: [
      { action: "Choose `Client A` in Visible category.", expected: "Only the Client A group and projects remain visible; Client B project rows disappear." },
      { action: "Start while a Client B project is selected, then choose Client A.", expected: "The main conversation switches to a Client A project so hidden client content is not left on screen." },
      { action: "Reload the page.", expected: "The Client A filter and a visible Client A conversation are restored." },
      { action: "Open project details and edit Project category.", expected: "The project moves to the new persisted category immediately." },
    ],
  },
  {
    slug: "project-terminal",
    title: "Workspace application tabs",
    group: "Core",
    summary: "Keep project-scoped terminal/TUI sessions alive while switching between top-bar tabs, and configure desktop launchers.",
    prerequisites: ["Select a project; standalone chats intentionally have no terminal.", "Install lazygit and nvim to exercise those launchers."],
    steps: [
      { action: "Click Terminal or press Cmd/Ctrl + backtick, then run `pwd`.", expected: "The Terminal tab connects and `pwd` is the selected project's canonical folder." },
      { action: "Invoke the same shortcut again, then reopen Terminal.", expected: "Chat becomes active and returning to Terminal shows the same live PTY instead of starting another shell." },
      { action: "Open lazygit and nvim in turn.", expected: "Each gets its own closable tab; nvim split borders are continuous because xterm is using its WebGL custom-glyph renderer." },
      { action: "Open Settings → Workspace tabs and add a desktop launcher such as `/usr/bin/open` with argument `.`.", expected: "The new tab appears for projects and opens the configured app on the daemon host without accepting command text from the browser." },
    ],
    notes: ["Workspace applications use Cascadia Code plus Nerd Font symbols. They are user-operated with the daemon user's permissions and are not agent sandbox tools."],
  },
  {
    slug: "image-paste",
    title: "Sandboxed image paste",
    group: "Core",
    summary: "Paste visual context into a project prompt and restore it safely after reload.",
    prerequisites: ["Select an idle folder project.", "Copy a PNG, JPEG, WebP, or GIF image to the clipboard."],
    steps: [
      { action: "Paste the image into the message composer.", expected: "A removable thumbnail appears without inserting binary text into the prompt." },
      { action: "Add a question and send.", expected: "The user message shows the image, the model can inspect it, and the daemon stores a generated attachment file inside the project sandbox." },
      { action: "Reload the page.", expected: "The image loads from the daemon's read-only project attachment endpoint and retains its original dimensions." },
      { action: "Try the same paste in a standalone chat.", expected: "The composer explains that image paste requires a folder-scoped project sandbox." },
    ],
  },
  {
    slug: "usage-cache-context",
    title: "Tokens, cache, and context",
    group: "Core",
    summary: "Track cumulative input/output, prompt-cache reads, endpoint-reported writes, and current context utilization.",
    prerequisites: ["Select `gpt-5.6-luna`.", "Use one conversation for both cache turns so its `prompt_cache_key` stays stable."],
    steps: [
      { action: "Send a prompt containing at least 1,024 tokens of stable text and ask for the exact reply `CACHE_SEEDED`.", expected: "Input and Output increase. Cache read is normally zero on this first unique prefix." },
      { action: "Send `Reply with exactly CACHE_HIT` in the same conversation; if that first short follow-up misses, send it once more.", expected: "Cache read becomes nonzero once routing reuses the eligible exact prefix with the same cache key." },
      { action: "Open details and compare the usage strip there with the conversation header.", expected: "Both show the same cumulative counters and current-context denominator of 372,000 for Luna." },
      { action: "Enter `/status`.", expected: "A local system message reports input, output, cache read, cache write, and context with the same values." },
    ],
    notes: [
      "The direct subscription endpoint currently omits `cache_write_tokens` even when a later hit proves the prefix was written. The UI displays the endpoint-reported value (usually 0) rather than estimating it.",
      "Prompt caching never reuses generated output; it only reuses an exact input prefix.",
    ],
  },
  {
    slug: "persistence-reconnect",
    title: "Persistence and reconnect",
    group: "Operations",
    summary: "Restore per-conversation SQLite history and catch up event gaps after a browser reconnect.",
    prerequisites: ["Keep one completed test conversation instead of deleting it."],
    steps: [
      { action: "Record the last assistant message and reload the browser page.", expected: "The client reconnects, reselects the saved conversation, and restores the same transcript and usage." },
      { action: "Open Connection, enter `ws://127.0.0.1:1/ws`, and reconnect.", expected: "The app goes offline but keeps the existing transcript visible; sending is disabled." },
      { action: "Restore the correct WebSocket URL.", expected: "The client reconnects, resubscribes, and catches up persisted events without duplicating messages." },
      { action: "Switch away and back once more.", expected: "The message order and cumulative usage remain stable." },
    ],
  },
];
